#!/usr/bin/env python3
import re
import sys
from pathlib import Path

TRANSLATIONS = {
    "$mode_name chains for IPv${family} cleanup completed": "$mode_name 链（IPv${family}）清理完成",
    "$mode_name chains for IPv${family} setup completed": "$mode_name 链（IPv${family}）设置完成",
    "APP_PROXY_ENABLE: $APP_PROXY_ENABLE": "APP_PROXY_ENABLE：$APP_PROXY_ENABLE",
    "APP_PROXY_MODE: $APP_PROXY_MODE": "APP_PROXY_MODE：$APP_PROXY_MODE",
    "Added MAC bypass rule for $mac": "已为 $mac 添加 MAC 旁路规则",
    "Added MAC proxy rule for $mac": "已为 $mac 添加 MAC 代理规则",
    "Added TCP rules to PREROUTING and OUTPUT chains": "已在 PREROUTING 与 OUTPUT 链添加 TCP 规则",
    "Added UDP rules to PREROUTING and OUTPUT chains": "已在 PREROUTING 与 OUTPUT 链添加 UDP 规则",
    "Added bypass for UID $uid": "已为 UID $uid 添加旁路",
    "Added bypass for core user $CORE_USER:$CORE_GROUP": "已为核心用户 $CORE_USER:$CORE_GROUP 添加旁路",
    "Added bypass for marked traffic with core mark $ROUTING_MARK": "已为标记为核心标记 $ROUTING_MARK 的流量添加旁路",
    "Added bypass rules for private IP ranges": "已添加私网地址段旁路规则",
    "Added ipset-based CN IP bypass rule": "已添加基于 ipset 的中国大陆 IP 旁路规则",
    "Added local address type bypass": "已添加本地地址类型旁路",
    "Added proxy for UID $uid": "已为 UID $uid 添加代理",
    "App blacklist mode enabled but no bypass apps configured": "应用黑名单模式已启用但未配置旁路应用",
    "App whitelist mode enabled but no proxy apps configured": "应用白名单模式已启用但未配置代理应用",
    "Application filtering requires NETFILTER_XT_MATCH_OWNER kernel feature which is not available": "分应用过滤需要 NETFILTER_XT_MATCH_OWNER 内核特性，但当前不可用",
    "BYPASS_APPS_LIST: $BYPASS_APPS_LIST": "BYPASS_APPS_LIST：$BYPASS_APPS_LIST",
    "BYPASS_CN_IP: $BYPASS_CN_IP": "BYPASS_CN_IP：$BYPASS_CN_IP",
    "BYPASS_MACS_LIST: $BYPASS_MACS_LIST": "BYPASS_MACS_LIST：$BYPASS_MACS_LIST",
    "CN IP bypass is disabled, skipping download": "已禁用中国大陆 IP 旁路，跳过下载",
    "CN IP bypass is disabled, skipping ipset cleanup": "已禁用中国大陆 IP 旁路，跳过 ipset 清理",
    "CN IP bypass is disabled, skipping ipset setup": "已禁用中国大陆 IP 旁路，跳过 ipset 设置",
    "CN IP file not found: $CN_IP_FILE": "未找到中国大陆 IPv4 列表文件：$CN_IP_FILE",
    "CN IPv6 file not found: $CN_IPV6_FILE": "未找到中国大陆 IPv6 列表文件：$CN_IPV6_FILE",
    "CN_IPV6_FILE: $CN_IPV6_FILE": "CN_IPV6_FILE：$CN_IPV6_FILE",
    "CN_IPV6_URL: $CN_IPV6_URL": "CN_IPV6_URL：$CN_IPV6_URL",
    "CN_IP_FILE: $CN_IP_FILE": "CN_IP_FILE：$CN_IP_FILE",
    "CN_IP_URL: $CN_IP_URL": "CN_IP_URL：$CN_IP_URL",
    "CORE_USER_GROUP: $CORE_USER_GROUP": "CORE_USER_GROUP：$CORE_USER_GROUP",
    "Cannot check kernel feature $feature: /proc/config.gz not available": "无法检查内核特性 $feature：/proc/config.gz 不可用",
    "Cannot read /data/system/packages.list": "无法读取 /data/system/packages.list",
    "Check PATH: $PATH": "请检查 PATH：$PATH",
    "Checking/Downloading China mainland IP list to $CN_IP_FILE": "正在检查/下载中国大陆 IPv4 列表到 $CN_IP_FILE",
    "Checking/Downloading China mainland IPv6 list to $CN_IPV6_FILE": "正在检查/下载中国大陆 IPv6 列表到 $CN_IPV6_FILE",
    "China IP list saved to $CN_IP_FILE": "中国大陆 IPv4 列表已保存到 $CN_IP_FILE",
    "China IPv6 list saved to $CN_IPV6_FILE": "中国大陆 IPv6 列表已保存到 $CN_IPV6_FILE",
    "Cleaning up $mode_name chains for IPv${family}": "正在清理 $mode_name 链（IPv${family}）",
    "Cleaning up IPv4 routing rules": "正在清理 IPv4 路由规则",
    "Cleaning up IPv6 routing rules": "正在清理 IPv6 路由规则",
    "Cleaning up REDIRECT chains": "正在清理 REDIRECT 链",
    "Cleaning up TPROXY chains": "正在清理 TPROXY 链",
    "Configuration loading completed": "配置加载完成",
    "Configuration validation failed": "配置校验失败",
    "Configuration validation passed": "配置校验通过",
    "Configuring interface proxy rules": "正在配置网口代理规则",
    "Core traffic bypass not configured, may cause traffic loop": "未配置核心流量旁路，可能导致流量循环",
    "DNS hijack enabled using REDIRECT mode to port $DNS_PORT": "DNS 劫持启用 REDIRECT 模式，目标端口 $DNS_PORT",
    "DNS hijack enabled using TPROXY mode": "DNS 劫持启用 TPROXY 模式",
    "DNS_HIJACK_ENABLE: $DNS_HIJACK_ENABLE": "DNS_HIJACK_ENABLE：$DNS_HIJACK_ENABLE",
    "DNS_PORT: $DNS_PORT": "DNS_PORT：$DNS_PORT",
    "DRY_RUN: $DRY_RUN": "DRY_RUN：$DRY_RUN",
    "Empty user or group detected, using defaults": "检测到空的用户或组，使用默认值",
    "Failed to add IPv4 route": "添加 IPv4 路由失败",
    "Failed to add IPv4 routing rule": "添加 IPv4 路由规则失败",
    "Failed to add IPv6 route": "添加 IPv6 路由失败",
    "Failed to add IPv6 routing rule": "添加 IPv6 路由规则失败",
    "Failed to create ipset 'cnip' or load IPv4 CIDR entries": "创建 ipset 'cnip' 或加载 IPv4 CIDR 条目失败",
    "Failed to create ipset 'cnip6' or load IPv6 CIDR entries": "创建 ipset 'cnip6' 或加载 IPv6 CIDR 条目失败",
    "Failed to download CN IP list, continuing without it": "下载中国大陆 IP 列表失败，将继续但不使用旁路",
    "Failed to download China IP list": "下载中国大陆 IPv4 列表失败",
    "Failed to download China IPv6 list": "下载中国大陆 IPv6 列表失败",
    "Failed to resolve UID for package: $package": "解析软件包 UID 失败：$package",
    "Failed to setup ipset, CN bypass disabled": "ipset 设置失败，中国大陆 IP 旁路已禁用",
    "Fetching latest China IP list from $CN_IP_URL": "正在从 $CN_IP_URL 获取最新中国大陆 IPv4 列表",
    "Fetching latest China IPv6 list from $CN_IPV6_URL": "正在从 $CN_IPV6_URL 获取最新中国大陆 IPv6 列表",
    "Final user:group configuration: '$CORE_USER:$CORE_GROUP'": "最终 user:group 配置：'$CORE_USER:$CORE_GROUP'",
    "HOTSPOT_INTERFACE: $HOTSPOT_INTERFACE": "HOTSPOT_INTERFACE：$HOTSPOT_INTERFACE",
    "Hotspot interface $HOTSPOT_INTERFACE will be proxied": "热点接口 $HOTSPOT_INTERFACE 将被代理",
    "Hotspot interface $HOTSPOT_INTERFACE will bypass proxy": "热点接口 $HOTSPOT_INTERFACE 将旁路代理",
    "Hotspot interface $WIFI_INTERFACE will be proxied": "热点接口 $WIFI_INTERFACE 将被代理",
    "IPv4 routing cleanup completed": "IPv4 路由清理完成",
    "IPv4 routing setup completed": "IPv4 路由设置完成",
    "IPv6 routing cleanup completed": "IPv6 路由清理完成",
    "IPv6 routing setup completed": "IPv6 路由设置完成",
    "IPv6: Kernel does not support IPv6 NAT or REDIRECT, skipping IPv6 DNS hijack": "IPv6：内核不支持 IPv6 NAT 或 REDIRECT，跳过 IPv6 DNS 劫持",
    "IPv6: Kernel does not support IPv6 NAT or REDIRECT, skipping IPv6 cleanup": "IPv6：内核不支持 IPv6 NAT 或 REDIRECT，跳过 IPv6 清理",
    "IPv6: Kernel does not support IPv6 NAT or REDIRECT, skipping IPv6 proxy setup": "IPv6：内核不支持 IPv6 NAT 或 REDIRECT，跳过 IPv6 代理设置",
    "Interface proxy rules configuration completed": "网口代理规则配置完成",
    "Invalid APP_PROXY_MODE: $APP_PROXY_MODE": "无效的 APP_PROXY_MODE：$APP_PROXY_MODE",
    "Invalid DNS_HIJACK_ENABLE: $DNS_HIJACK_ENABLE (must be 0=disabled, 1=tproxy, 2=redirect)": "无效的 DNS_HIJACK_ENABLE：$DNS_HIJACK_ENABLE（必须是 0=disabled，1=tproxy，2=redirect）",
    "Invalid DNS_PORT: $DNS_PORT": "无效的 DNS_PORT：$DNS_PORT",
    "Invalid MAC_PROXY_MODE: $MAC_PROXY_MODE": "无效的 MAC_PROXY_MODE：$MAC_PROXY_MODE",
    "Invalid MARK_VALUE6: $MARK_VALUE6": "无效的 MARK_VALUE6：$MARK_VALUE6",
    "Invalid MARK_VALUE: $MARK_VALUE": "无效的 MARK_VALUE：$MARK_VALUE",
    "Invalid PROXY_MODE: $PROXY_MODE (must be 0=auto, 1=force TPROXY, 2=force REDIRECT)": "无效的 PROXY_MODE：$PROXY_MODE（必须是 0=auto，1=force TPROXY，2=force REDIRECT）",
    "Invalid PROXY_TCP_PORT: $PROXY_TCP_PORT": "无效的 PROXY_TCP_PORT：$PROXY_TCP_PORT",
    "Invalid PROXY_UDP_PORT: $PROXY_UDP_PORT": "无效的 PROXY_UDP_PORT：$PROXY_UDP_PORT",
    "Invalid TABLE_ID: $TABLE_ID": "无效的 TABLE_ID：$TABLE_ID",
    "Invalid UID format for package: $pkg": "软件包 $pkg 的 UID 格式无效",
    "Invalid user prefix in token: $token, using 0": "令牌 $token 的用户前缀无效，使用 0",
    "Kernel TPROXY support confirmed": "已确认内核支持 TPROXY",
    "Kernel TPROXY support not available": "内核不支持 TPROXY",
    "Kernel does not support TPROXY, falling back to REDIRECT mode (auto)": "内核不支持 TPROXY，自动回退到 REDIRECT 模式",
    "Kernel does not support ipset (CONFIG_IP_SET, CONFIG_NETFILTER_XT_SET). Cannot bypass CN IPs": "内核不支持 ipset（CONFIG_IP_SET, CONFIG_NETFILTER_XT_SET），无法旁路中国大陆 IP",
    "Kernel feature $feature is disabled or not found": "内核特性 $feature 被禁用或未找到",
    "Kernel feature $feature is enabled": "内核特性 $feature 已启用",
    "Kernel supports TPROXY, using TPROXY mode (auto)": "内核支持 TPROXY，自动使用 TPROXY 模式",
    "Loading IPv4 CIDR from $CN_IP_FILE": "正在从 $CN_IP_FILE 加载 IPv4 CIDR",
    "Loading IPv6 CIDR from $CN_IPV6_FILE": "正在从 $CN_IPV6_FILE 加载 IPv6 CIDR",
    "Loading configuration from environment or defaults...": "从环境变量或默认值加载配置...",
    "MAC blacklist mode enabled but no bypass MACs configured": "MAC 黑名单模式已启用但未配置旁路 MAC",
    "MAC filtering requires NETFILTER_XT_MATCH_MAC kernel feature which is not available": "MAC 过滤需要 NETFILTER_XT_MATCH_MAC 内核特性，但当前不可用",
    "MAC whitelist mode enabled but no proxy MACs configured": "MAC 白名单模式已启用但未配置代理 MAC",
    "MAC_FILTER_ENABLE: $MAC_FILTER_ENABLE": "MAC_FILTER_ENABLE：$MAC_FILTER_ENABLE",
    "MAC_PROXY_MODE: $MAC_PROXY_MODE": "MAC_PROXY_MODE：$MAC_PROXY_MODE",
    "MARK_VALUE6: $MARK_VALUE6": "MARK_VALUE6：$MARK_VALUE6",
    "MARK_VALUE: $MARK_VALUE": "MARK_VALUE：$MARK_VALUE",
    "MOBILE_INTERFACE: $MOBILE_INTERFACE": "MOBILE_INTERFACE：$MOBILE_INTERFACE",
    "Missing required commands: $missing": "缺少必要的命令：$missing",
    "Mobile interface $MOBILE_INTERFACE will be proxied": "移动数据接口 $MOBILE_INTERFACE 将被代理",
    "Mobile interface $MOBILE_INTERFACE will bypass proxy": "移动数据接口 $MOBILE_INTERFACE 将旁路代理",
    "Multiple commands specified.": "检测到多个命令参数",
    "Must run with root privileges": "必须以 root 权限运行",
    "PROXY_APPS_LIST: $PROXY_APPS_LIST": "PROXY_APPS_LIST：$PROXY_APPS_LIST",
    "PROXY_HOTSPOT: $PROXY_HOTSPOT": "PROXY_HOTSPOT：$PROXY_HOTSPOT",
    "PROXY_IPV6: $PROXY_IPV6": "PROXY_IPV6：$PROXY_IPV6",
    "PROXY_MACS_LIST: $PROXY_MACS_LIST": "PROXY_MACS_LIST：$PROXY_MACS_LIST",
    "PROXY_MOBILE: $PROXY_MOBILE": "PROXY_MOBILE：$PROXY_MOBILE",
    "PROXY_MODE: $PROXY_MODE": "PROXY_MODE：$PROXY_MODE",
    "PROXY_TCP: $PROXY_TCP": "PROXY_TCP：$PROXY_TCP",
    "PROXY_TCP_PORT: $PROXY_TCP_PORT": "PROXY_TCP_PORT：$PROXY_TCP_PORT",
    "PROXY_UDP: $PROXY_UDP": "PROXY_UDP：$PROXY_UDP",
    "PROXY_UDP_PORT: $PROXY_UDP_PORT": "PROXY_UDP_PORT：$PROXY_UDP_PORT",
    "PROXY_USB: $PROXY_USB": "PROXY_USB：$PROXY_USB",
    "PROXY_WIFI: $PROXY_WIFI": "PROXY_WIFI：$PROXY_WIFI",
    "Package not found in packages.list: $pkg": "在 packages.list 中未找到软件包：$pkg",
    "Parsed user:group as '$CORE_USER:$CORE_GROUP'": "解析得到 user:group：'$CORE_USER:$CORE_GROUP'",
    "Proxy restarted": "代理已重启",
    "Proxy setup completed": "代理设置完成",
    "Proxy stopped": "代理已停止",
    "REDIRECT mode only supports TCP": "REDIRECT 模式仅支持 TCP",
    "REDIRECT mode rules added": "已添加 REDIRECT 模式规则",
    "ROUTING_MARK: $ROUTING_MARK": "ROUTING_MARK：$ROUTING_MARK",
    "Resolved package $token to UID $final_uid": "已将软件包 $token 解析到 UID $final_uid",
    "Restarting proxy...": "正在重启代理...",
    "Setting up $mode_name chains for IPv${family}": "正在设置 $mode_name 链（IPv${family}）",
    "Setting up MAC address filter rules for interface $HOTSPOT_INTERFACE": "正在为接口 $HOTSPOT_INTERFACE 设置 MAC 过滤规则",
    "Setting up application filter rules in $APP_PROXY_MODE mode": "正在以 $APP_PROXY_MODE 模式设置应用过滤规则",
    "Setting up ipset for China mainland IPs": "正在为中国大陆 IP 设置 ipset",
    "Setting up routing rules for IPv4": "正在设置 IPv4 路由规则",
    "Setting up routing rules for IPv6": "正在设置 IPv6 路由规则",
    "Starting proxy setup...": "正在开始代理设置...",
    "Stopping proxy...": "正在停止代理...",
    "Successfully loaded $ipv4_count IPv4 CIDR entries": "已成功加载 $ipv4_count 条 IPv4 CIDR",
    "Successfully loaded $ipv6_count IPv6 CIDR entries": "已成功加载 $ipv6_count 条 IPv6 CIDR",
    "TABLE_ID: $TABLE_ID": "TABLE_ID：$TABLE_ID",
    "TPROXY mode forced but kernel does not support TPROXY": "已强制 TPROXY 模式但内核不支持 TPROXY",
    "TPROXY mode rules added": "已添加 TPROXY 模式规则",
    "USB interface $USB_INTERFACE will be proxied": "USB 接口 $USB_INTERFACE 将被代理",
    "USB interface $USB_INTERFACE will bypass proxy": "USB 接口 $USB_INTERFACE 将旁路代理",
    "USB_INTERFACE: $USB_INTERFACE": "USB_INTERFACE：$USB_INTERFACE",
    "Usage: %s {start|stop|restart} [--dry-run]": "用法：%s {start|stop|restart} [--dry-run]",
    "Usage: %s {start|stop|restart} [--dry-run]\\n": "用法：%s {start|stop|restart} [--dry-run]\\n",
    "Using REDIRECT mode (forced by configuration)": "按照配置强制使用 REDIRECT 模式",
    "Using TPROXY mode (forced by configuration)": "按照配置强制使用 TPROXY 模式",
    "Using default user:group '$CORE_USER:$CORE_GROUP'": "使用默认 user:group '$CORE_USER:$CORE_GROUP'",
    "Using existing China IP list: $CN_IP_FILE": "使用已存在的中国大陆 IPv4 列表：$CN_IP_FILE",
    "Using existing China IPv6 list: $CN_IPV6_FILE": "使用已存在的中国大陆 IPv6 列表：$CN_IPV6_FILE",
    "Validating configuration...": "正在校验配置...",
    "WIFI_INTERFACE: $WIFI_INTERFACE": "WIFI_INTERFACE：$WIFI_INTERFACE",
    "WiFi interface $WIFI_INTERFACE will be proxied": "WiFi 接口 $WIFI_INTERFACE 将被代理",
    "WiFi interface $WIFI_INTERFACE will bypass proxy": "WiFi 接口 $WIFI_INTERFACE 将旁路代理",
    "[DRY-RUN] $cmd $args": "[DRY-RUN] $cmd $args",
    "[DRY-RUN] Skip dependency check": "[DRY-RUN] 跳过依赖检查",
    "[DRY-RUN] Skip kernel feature check for $1": "[DRY-RUN] 跳过内核特性检查 $1",
    "[DRY-RUN] Skip root check": "[DRY-RUN] 跳过 root 检查",
    "[DRY-RUN] TPROXY support check skipped": "[DRY-RUN] 跳过 TPROXY 支持检查",
    "[DRY-RUN] Would load $ipv4_count IPv4 CIDR entries via ipset restore": "[DRY-RUN] 将通过 ipset restore 加载 $ipv4_count 条 IPv4 CIDR",
    "[DRY-RUN] Would load $ipv6_count IPv6 CIDR entries via ipset restore": "[DRY-RUN] 将通过 ipset restore 加载 $ipv6_count 条 IPv6 CIDR",
    "[DRY-RUN] curl -fsSL --connect-timeout 10 --retry 3 $CN_IPV6_URL -o $CN_IPV6_FILE.tmp": "[DRY-RUN] curl -fsSL --connect-timeout 10 --retry 3 $CN_IPV6_URL -o $CN_IPV6_FILE.tmp",
    "[DRY-RUN] curl -fsSL --connect-timeout 10 --retry 3 $CN_IP_URL -o $CN_IP_FILE.tmp": "[DRY-RUN] curl -fsSL --connect-timeout 10 --retry 3 $CN_IP_URL -o $CN_IP_FILE.tmp",
    "[DRY-RUN] echo 0 > /proc/sys/net/ipv4/ip_forward": "[DRY-RUN] echo 0 > /proc/sys/net/ipv4/ip_forward",
    "[DRY-RUN] echo 0 > /proc/sys/net/ipv6/conf/all/forwarding": "[DRY-RUN] echo 0 > /proc/sys/net/ipv6/conf/all/forwarding",
    "[DRY-RUN] echo 1 > /proc/sys/net/ipv4/ip_forward": "[DRY-RUN] echo 1 > /proc/sys/net/ipv4/ip_forward",
    "[DRY-RUN] echo 1 > /proc/sys/net/ipv6/conf/all/forwarding": "[DRY-RUN] echo 1 > /proc/sys/net/ipv6/conf/all/forwarding",
    "[DRY-RUN] ip -6 route $*": "[DRY-RUN] ip -6 route $*",
    "[DRY-RUN] ip -6 route add local ::/0 dev lo table $TABLE_ID": "[DRY-RUN] ip -6 route add local ::/0 dev lo table $TABLE_ID",
    "[DRY-RUN] ip -6 route del local ::/0 dev lo table $TABLE_ID": "[DRY-RUN] ip -6 route del local ::/0 dev lo table $TABLE_ID",
    "[DRY-RUN] ip -6 rule $*": "[DRY-RUN] ip -6 rule $*",
    "[DRY-RUN] ip -6 rule add fwmark $MARK_VALUE6 lookup $TABLE_ID": "[DRY-RUN] ip -6 rule add fwmark $MARK_VALUE6 lookup $TABLE_ID",
    "[DRY-RUN] ip -6 rule del fwmark $MARK_VALUE6 table $TABLE_ID pref $TABLE_ID": "[DRY-RUN] ip -6 rule del fwmark $MARK_VALUE6 table $TABLE_ID pref $TABLE_ID",
    "[DRY-RUN] ip route $*": "[DRY-RUN] ip route $*",
    "[DRY-RUN] ip route add local 0.0.0.0/0 dev lo table $TABLE_ID": "[DRY-RUN] ip route add local 0.0.0.0/0 dev lo table $TABLE_ID",
    "[DRY-RUN] ip route del local 0.0.0.0/0 dev lo table $TABLE_ID": "[DRY-RUN] ip route del local 0.0.0.0/0 dev lo table $TABLE_ID",
    "[DRY-RUN] ip rule $*": "[DRY-RUN] ip rule $*",
    "[DRY-RUN] ip rule add fwmark $MARK_VALUE lookup $TABLE_ID": "[DRY-RUN] ip rule add fwmark $MARK_VALUE lookup $TABLE_ID",
    "[DRY-RUN] ip rule del fwmark $MARK_VALUE table $TABLE_ID pref $TABLE_ID": "[DRY-RUN] ip rule del fwmark $MARK_VALUE table $TABLE_ID pref $TABLE_ID",
    "[DRY-RUN] ipset create cnip hash:net family inet hashsize 8192 maxelem 65536": "[DRY-RUN] ipset create cnip hash:net family inet hashsize 8192 maxelem 65536",
    "[DRY-RUN] ipset create cnip6 hash:net family inet6 hashsize 8192 maxelem 65536": "[DRY-RUN] ipset create cnip6 hash:net family inet6 hashsize 8192 maxelem 65536",
    "[DRY-RUN] ipset destroy cnip": "[DRY-RUN] ipset destroy cnip",
    "[DRY-RUN] ipset destroy cnip6": "[DRY-RUN] ipset destroy cnip6",
    "ipset '$ipset_name' not available, skipping CN IP bypass": "ipset '$ipset_name' 不可用，跳过中国大陆 IP 旁路",
    "ipset 'cnip' and 'cnip6' destroyed": "ipset 'cnip' 与 'cnip6' 已销毁",
    "ipset 'cnip' loaded with China mainland IPs": "ipset 'cnip' 已加载中国大陆 IPv4",
    "ipset 'cnip6' loaded with China mainland IPv6 IPs": "ipset 'cnip6' 已加载中国大陆 IPv6",
    "ipset not found. Cannot bypass CN IPs": "未找到 ipset，无法旁路中国大陆 IP",
}

COMMENT_TRANSLATIONS = {
    "Configuration (modify as needed)": "配置（可按需修改）",
    "Proxy core configuration": "代理核心配置",
    "Proxy running user and group": "代理运行的用户和组",
    "Proxy traffic mark": "代理流量标记",
    "Proxy ports (transparent proxy listening ports)": "代理端口（透明代理监听端口）",
    "Proxy mode: 0=auto (check TPROXY support), 1=force TPROXY, 2=force REDIRECT": "代理模式：0=自动（检测 TPROXY 支持），1=强制 TPROXY，2=强制 REDIRECT",
    "Proxy mode: 0=auto, 1=force TPROXY, 2=force REDIRECT": "代理模式：0=自动，1=强制 TPROXY，2=强制 REDIRECT",
    "DNS configuration": "DNS 配置",
    "DNS hijack method (0: disabled, 1: tproxy, 2: redirect)": "DNS 劫持方式（0：禁用，1：tproxy，2：redirect）",
    "DNS listening port": "DNS 监听端口",
    "Interface definitions": "网口定义",
    "Mobile data interface": "移动数据接口",
    "WiFi interface": "WiFi 接口",
    "Hotspot interface": "热点接口",
    "USB tethering interface": "USB 共享网接口",
    "Proxy switches": "代理开关",
    "Mark values": "标记值",
    "Routing table ID": "路由表 ID",
    "Per-app proxy (use space to separate package names, supports user:package format)": "分应用代理（用空格分隔包名，支持 user:package 格式）",
    "Per-app proxy": "分应用代理",
    "Example: \"com.example.app com.other\"": "例：\"com.example.app com.other\"",
    "Example: \"com.android.shell\"": "例：\"com.android.shell\"",
    "\"blacklist\" or \"whitelist\"": "\"blacklist\" 或 \"whitelist\"",
    "CN IP bypass configuration": "中国大陆 IP 旁路配置",
    "CN IP bypass": "中国大陆 IP 旁路",
    "CN IP list file paths": "中国大陆 IP 列表文件路径",
    "CN IP source URLs": "中国大陆 IP 源地址",
    "MAC address blacklist/whitelist configuration (hotspot mode)": "MAC 地址黑/白名单配置（热点模式）",
    "MAC address blacklist/whitelist (use space to separate MAC addresses)": "MAC 地址黑/白名单（用空格分隔 MAC 地址）",
    "MAC address filtering": "MAC 地址过滤",
    "Example: \"AA:BB:CC:DD:EE:FF 11:22:33:44:55:66\"": "例：\"AA:BB:CC:DD:EE:FF 11:22:33:44:55:66\"",
    "Example: \"FF:EE:DD:CC:BB:AA\"": "例：\"FF:EE:DD:CC:BB:AA\"",
    "Dry-run mode (disabled by default)": "演练模式（默认关闭）",
    "Unified command wrapper functions": "统一的命令封装函数",
    "Re-download if file doesn't exist or is older than 7 days": "若文件不存在或超过 7 天则重新下载",
    "Unified setup function for both IPv4 and IPv6 with mode selection": "面向 IPv4/IPv6 的统一设置函数，带模式选择",
    "tproxy or redirect": "tproxy 或 redirect",
    "Set mode name for logging": "设置日志用的模式名称",
    "Define chains based on family": "根据协议族定义链",
    "Create chains": "创建链",
    "Add private IP ranges based on family": "按协议族添加私网地址段",
    "Add rules to main chains": "加入主链路规则",
    "Handle DNS from interfaces in PREROUTING chain (DNS_HIJACK_PRE)": "在 PREROUTING 链处理来自接口的 DNS（DNS_HIJACK_PRE）",
    "Handle local DNS hijacking in OUTPUT chain (DNS_HIJACK_OUT)": "在 OUTPUT 链处理本地 DNS 劫持（DNS_HIJACK_OUT）",
    "Handle DNS using REDIRECT method": "使用 REDIRECT 方式处理 DNS",
    "Unified cleanup function for both IPv4 and IPv6 with mode selection": "面向 IPv4/IPv6 的统一清理函数，带模式选择",
    "Remove rules from main chains": "从主链移除规则",
    "Clean up chains": "清空并删除链",
    "Remove DNS rules if applicable": "如适用，删除 DNS 规则",
}

LOG_PATTERN = re.compile(r"log\\s+\\w+\\s+\"(.*?)\"")
COMMENT_PATTERN = re.compile(r"^(\\s*#)\\s?(.*)$")


def translate_line(line: str) -> str:
    m = LOG_PATTERN.search(line)
    if m:
        msg = m.group(1)
        if msg in TRANSLATIONS:
            line = line.replace(msg, TRANSLATIONS[msg])
        return line
    m = COMMENT_PATTERN.match(line)
    if m:
        prefix, text = m.groups()
        translated = COMMENT_TRANSLATIONS.get(text)
        if translated:
            return f"{prefix} {translated}"
    return line


def ensure_ipv6_enabled(text: str) -> str:
    return re.sub(r"readonly\\s+DEFAULT_PROXY_IPV6=0", "readonly DEFAULT_PROXY_IPV6=1", text)


def main():
    if len(sys.argv) != 2:
        print("Usage: translate_tproxy.py <path>")
        sys.exit(1)
    target = Path(sys.argv[1])
    content = target.read_text()
    lines = content.splitlines()
    translated_lines = [translate_line(line) for line in lines]
    output = "\n".join(translated_lines) + "\n"
    output = ensure_ipv6_enabled(output)
    target.write_text(output)


if __name__ == "__main__":
    main()
